spring:
  application:
    name: wow-server
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/acore_auth
    username: root
    password: Loquendo96@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
google:
  api-secret:  "6LdCTaoqAAAAABzI5dvITaOy6A8FnoTCtdQlUTuH"